language: node_js
node_js:
  - "6"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - chmod +x ./.build_scripts/deploy.sh
  - chmod +x ./.build_scripts/lint.sh

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_script:
- ./.build_scripts/lint.sh
- yarn test

script:
- yarn run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
